### ISSUE TITLE
How to create dynamic DOM binding using formly?

### ISSUE THREAD

**Issue by WildHagai** [arabdevelop/svelte-formly#13]
Is there a way to create a text input with it's value binded to a selection from a "select" element?

let's assume the fields variable is set to this:

```
[{
      type: "text",
      name: "number",
      value: "",
      id: "number",
},
{
      type: "select",
      name: "city",
      id: "city",
      label: "City",
      validation: ["required"],
      options: [
        {
          value: 1,
          title: "Agadir"
        },
        {
          value: 2,
          title: "Casablanca"
        }
      ]
    }]
```

I want the value of the "number" text input to be set to the value of the selected city, if it's Agadir, then the text will be 1.

or better yet, I want the value of the text input to be set to a value returning from a function accepting a parameter from the value of the selection.

Is there a way to bind the input to a variable? that way I can make a reactive statement using the value of the selection to set the value of the text input.

**Comment by WildHagai** [comment]
> Is there a way to create a text input with it's value binded to a selection from a "select" element?
> 
> let's assume the fields variable is set to this:
> `[{
> type: "text",
> name: "number",
> value: "",
> id: "number",
> },
> 
> {
> type: "select",
> name: "city",
> id: "city",
> label: "City",
> validation: ["required"],
> options: [
> {
> value: 1,
> title: "Agadir"
> },
> {
> value: 2,
> title: "Casablanca"
> }
> ]
> }]`
> I want the value of the "number" text input to be set to the value of the selected city, if it's Agadir, then the text will be 1.
> 
> or better yet, I want the value of the text input to be set to a value returning from a function accepting a parameter from the value of the selection.
> 
> Is there a way to bind the input to a variable? that way I can make a reactive statement using the value of the selection to set the value of the text input.

**Comment by kamalkech** [comment]
I create a simple example for you 

```
<script>
  import { onMount } from "svelte";
  import { Field, valuesForm } from "svelte-formly";

  let fields = [
    {
      type: "text",
      name: "number",
      value: "",
      id: "number"
    },
    {
      type: "select",
      name: "city",
      id: "city",
      label: "City",
      validation: ["required"],
      options: [
        {
          value: 1,
          title: "Agadir"
        },
        {
          value: 2,
          title: "Casablanca"
        },
        {
          value: 3,
          title: "Rabat"
        }
      ]
    }
  ];

  onMount(() => {
    valuesForm.subscribe(data => {
      const values = data.values;
      if (typeof values !== "undefined") {
        onChangeValue(values.city);
      }
    });
  });

  function onChangeValue(val) {
    fields = fields.map(item => {
      if (item.name === "number") {
        item = {
          ...item,
          value: val
        };
      }
      return item;
    });
  }
</script>

<form>
  <Field {fields} />
</form>
```
`
`
