### ISSUE TITLE
<Radio> was created with unknown prop 'items'

### ISSUE THREAD

**Issue by larmcr** [arabdevelop/svelte-formly#14]
Hi! First at all, thanks for this library!

Second, I think I found an issue with `Radio` component: when I use the example in README, this warning appears on browser's console:
```console
<Radio> was created with unknown prop 'items'
```
I noticed the `Radio` component is expected a prop named _radios_:
```js
export let radios = [];
```
but the `Field` component is sending a prop named _items_:
```js
...
{:else if field.type === 'radio'}
      <Radio
        name={field.name}
        classe={field.class}
        items={field.items}
        aligne={field.aligne}
        on:changeValue={changeValueHander} />
...
```
I'm using package version `0.0.16`.

BTW, I tried to change the prop name in `Field` component, compiled it and used it. The warning disappeared but the radio element (HTML) was not shown.

Thanks in advance.

**Comment by kamalkech** [comment]
the attributes is renamed now, you can use the last version 0.0.17
