### ISSUE TITLE
Instructions update

### ISSUE THREAD

**Issue by kuhlaid** [arabdevelop/svelte-formly#17]
I would suggest updating the instruction to use valid JSON for the 'const fields' value. Instead of using
```
const fields = [
    {
      type: "color",
      name: "color",
      id: "color",
      label: "Color Form"
    }...
```
use
```
const fields = [
    {
      "type": "color",
      "name": "color",
      "id": "color",
      "label": "Color Form"
    }...
```
This module is super helpful, so thank you for creating it. The reason I suggest the change to the instructions is I store the 'const fields' JSON values in indexedDb and dynamically load it into my Svelte app and simply use JSON.parse() to assign the value to the fields variable. If the fields value is not valid JSON this does not work.

**Comment by kamalkech** [comment]
The both work fine.

1- Test the both samples
2- Close this issue plz :)
