### ISSUE TITLE
Readonly / disabled options

### ISSUE THREAD

**Issue by rawoke083** [arabdevelop/svelte-formly#18]
Hi , great library. How would one go about making fields readonly either at declaration or dynamically ?

**Comment by kamalkech** [comment]
Thank you to choose my library for your projects

For your question, you need to :

1- Update to svelte-formly@0.0.18
2- Add attribute "readonly" to your field like : 
```
  {
    ...
    readonly: true,
    ...
  }
```

**Comment by rawoke083** [comment]
Thank you
