### ISSUE TITLE
On Examples page, there is no label on the radio text

### ISSUE THREAD

**Issue by tranKILL** [arabdevelop/svelte-formly#23]
May be you want it like that, but there is label on all the others :p
Except that, seems great :D ;)

**Comment by kamalkech** [comment]
@tranKILL you can add label attributes : https://svelte.dev/repl/439ef3dfbfdb44b2ad2131e7ca508c6e?version=3.37.0

**Comment by tranKILL** [comment]
Thanks for the answer ;)
No radio box on it

Cannot click on Male or Female to select linked radio box on this page https://documentation-svelte-formly.vercel.app/examples
