### ISSUE TITLE
Form Layout

### ISSUE THREAD

**Issue by leejoramo-d51** [arabdevelop/svelte-formly#30]
Is there a way to layout the form and not just automatically generate a vertically stacked form?

Instead of having this in my `Component.svelte`:

```svelte

      <Field {fields} />

```
I want to place each field in a layout:

```svelte
<div class='row'>
  <div class='col'>
    <Field {fields} name='x' />
  </div>
  <div class='col'>
    <Field {fields} name='y' />
  </div>
  <div class='col'>
    <Field {fields} name='total' />
  </div>
</div>
<div class='row'>
  <div class='col'>
    <Field {fields} name='category' />
  </div>
  <div class='col'>
    <Field {fields} name='items' />
  </div>
</div>
```

**Comment by kamalkech** [comment]
first of all  your code is not correct because``` <Field {fields} />``` this is a collection of fields not juste one field.
check this solution:

- add prefix attributes to choose type of wrapper (div, fieldset...etc) and add classes for each wrapper, ex: [https://svelte.dev/repl/304843b8e4f143119b30df9a936fbe2f?version=3.38.0](https://svelte.dev/repl/304843b8e4f143119b30df9a936fbe2f?version=3.38.0)

hop that help you, and close if is Ok for you ;)

**Comment by leejoramo-d51** [comment]
Thank You!  This will work for most of my use cases. 

My above code was intended to be more of a example of what I was trying to achieve,  not "real" code. 

For the last six months in my spare time,  I have been reviewing Svelte form tools. I keep coming back to yours. Some of my forms will be partly automatically generated based on API calls to a back end. I can see how to build this using your system much more easily than other form systems. Additionally, I like the clear Widgets (or Component) method used by Formly. 

Most importantly, I can read your code and fit it in my mind. The other Svelte form projects either are too simple, or have complex external dependencies for validation and widgets.

**Comment by kamalkech** [comment]
@leejoramo-d51 happy to get good answer
for svelte-formly i try to make it more easy  with minimal code lines to build a reactive forms, with current version 1.0.2 i focus on reactivite like new feature "preprocess", about override template for each field may be in the futur version.
