### ISSUE TITLE
Fields not rendering when field source isn't named "fields"

### ISSUE THREAD

**Issue by CaelumF** [arabdevelop/svelte-formly#33]
Hello, when I attempt to use the `<Field {fields}>` component with a variable called `fields`, it works fine. If I change `fields` to `fieldz`, it doesn't render the forms

If someone can confirm that it works with a different name for them I'll try to provide a min. reproducible :)

And the purpose:

I'm trying to have a separate form show in a popup

**Comment by kamalkech** [comment]
@CaelumF 

the compenant Field require props with name fields so you can do like this example : 

```typescript
const fieldz = [ .... ]

<Field fields={ fieldz } />
```

**Comment by CaelumF** [comment]
Ah silly me, thanks!

**Comment by kamalkech** [comment]
welcome ;)
