### ISSUE TITLE
Create really dynamic forms on-the-fly?

### ISSUE THREAD

**Issue by bluepuma77** [arabdevelop/svelte-formly#35]
Hi @kamalkech,

before I dig deeper in this great looking library:

Is it possible to use svelte-formly with really dynamic data? Can I create a form on-the-fly with some JSON from the backend? Have a different form for every user?

Or does the JSON form need to be fixed before the Svelte compilation?

Thanks,
bluepuma

**Comment by lingster** [comment]
Hi, we've just started using this library and it looks great. I think you should be able to supply json dynamically, eg via a rest api. So you could add something like a call via axios/fetch to retreive the form definitions then supply that as input to formly.

**Comment by kamalkech** [comment]
@bluepuma77 @lingster yes sure you can use a dynamic data from external API

you can check bellow an example that you fetch a data fields from nestjs with endpoint **http://localhost:3000/fields** hop this example help you.

svelte-formly give you more reactivity for your form using precrocess hook, for details check here https://documentation-svelte-formly.vercel.app/guide/preprocess

```typescript
<script lang="ts">
  import { get } from 'svelte/store';
  import { valuesForm, Field } from 'svelte-formly';
  import { onMount } from 'svelte';

  let fields;
  onMount(async () => {
    const res = await fetch('http://localhost:3000/fields');
    fields = await res.json();
  });

  let message: string = '';
  let values: any = {};
  function onSubmit() {
    const data: any = get(valuesForm);
    values = data.values;
    if (data.valid) {
      message = 'Congratulation! now your form is valid';
    } else {
      message = 'Your form is not valid!';
    }
  }
</script>

<ul>
  <li>Message: {message}</li>
  <li>Values: {JSON.stringify(values)}</li>
</ul>
<form on:submit|preventDefault={onSubmit}>
  <hr />
  {#if fields}
    <Field {fields} />
  {/if}
  <button class="btn btn-secondary btn-lg btn-block" type="submit"
    >Submit</button
  >
</form>

```

**Comment by bluepuma77** [comment]
Beautiful example, thank you!

**Comment by kamalkech** [comment]
welcome, after update sveltejs i will update svelte-formly for field type select,coming soon
