### ISSUE TITLE
Question regarding license

### ISSUE THREAD

**Issue by bluepuma77** [arabdevelop/svelte-formly#38]
Hi svelte-formly team,

there has been some [issues](https://github.com/arabdevelop/svelte-formly/issues/34) and [discussions](https://www.reddit.com/r/sveltejs/comments/qiu4nl/in_react_land_people_always_use_form_libs_how_is/) around your "GPL-3.0 License". Many developers see the use of GPL-3 as forcing them to open-source their own code, so they can't use your library. (Is Javascript downloaded and run in a browser already "distribute code"? Lawyers will argue about it)

Just wanted to create awareness about this and that it would help adoption of your library if you change to a license like MIT or Apache License 2.0. Of course, if this is what you want. 

@arabdevelop @kamalkech A comment about this would be nice, so other developers know if there might be a change of license.

Cheers

**Comment by kamalkech** [comment]
@bluepuma77 that s exactly what i try to update today and it s already done, but another question, why almost developers like this package but not found them on stargazers list ?!!

**Comment by mbingel** [comment]
Awesome, thanks! 

Sorry, I can't answer your stargazer question.

**Comment by bluepuma77** [comment]
Thanks, that's great, I really appreciate it!

And sorry, I can not answer your stargazer question.
