### ISSUE TITLE
Radio buttons - do not check any button by default?

### ISSUE THREAD

**Issue by hauselin** [arabdevelop/svelte-formly#39]
By default, it seems like the first radio button is always checked even when I haven't clicked on anything yet. Is it possible to make it such that no button is checked by default? Thanks!

![image](https://user-images.githubusercontent.com/7620977/142800093-492b319c-deb4-422b-b13a-f067c6b31f68.png)

**Comment by kamalkech** [comment]
@hauselin For your case it s better to use checkbox instead of radio that require to select a value and by default take the first element value if not selected,

Check this [example](https://svelte.dev/repl/b9ba95857a5c4bf5bbeb8763d3f3c151?version=3.44.2) for checkbox and hope that help you

**Comment by hauselin** [comment]
Ok, thanks for the suggestion!

**Comment by kamalkech** [comment]
@hauselin welcome
