### ISSUE TITLE
Documentation on Custom Field Types

### ISSUE THREAD

**Issue by firrae** [arabdevelop/svelte-formly#40]
Hi there, just curious if there is documentation on how to add custom field types? I'd like to create a duo of custom file upload form fields but I'm not sure how that would be implemented in this library?

Any help is appreciated.

**Comment by kamalkech** [comment]
@firrae this package is an UI form for sveltejs, with current version you cannot create your own fields types but on this package you can found most field types, and there is a file upload type, check this link https://documentation-svelte-formly.vercel.app/ui/file

**Comment by Lucasmiguelmac** [comment]
> @firrae this package is an UI form for sveltejs, with current version you cannot create your own fields types but on this package you can found most field types, and there is a file upload type, check this link https://documentation-svelte-formly.vercel.app/ui/file

Is there a plan for custom fields in the future? It would be a game changer for this library imo.
