### ISSUE TITLE
Default value on autocomplete and select field.

### ISSUE THREAD

**Issue by Lucasmiguelmac** [arabdevelop/svelte-formly#41]
Hello there. It would be nice to have a default submittable value option on both of the following fielts:
- Select
- Autocomplete

**Comment by kamalkech** [comment]
@Lucasmiguelmac thank you for asking, try to do :

- Check this [repl](https://svelte.dev/repl/3a58d8a23e6f4779b1b1d0bda84a64d1?version=3.46.4)  as example and make sure you install last version 1.1.2 (released today) if you try to test on your local project

**Comment by Lucasmiguelmac** [comment]
> @Lucasmiguelmac thank you for asking, try to do :
> 
>     * Check this [repl](https://svelte.dev/repl/3a58d8a23e6f4779b1b1d0bda84a64d1?version=3.46.4)  as example and make sure you install last version 1.1.2 (released today) if you try to test on your local project

Hi. Just checked the repl. Default value wont't work if you set `multiple` to false. Made a fork of your repl for you to see:
https://svelte.dev/repl/7d3c145bc9ca4e659831c783f64a78e9?version=3.46.4

**Comment by kamalkech** [comment]
cannot understand what do u mean, if you want to add multiple values to field autocomplete you can do :
```typescript
value: [
  {
    value: 2,
    title: "item 2",
  },
  {
    value: 4,
    title: "item 4",
  },
]
```

and that s what i get : 
![DeepinScreenshot_select-area_20220328212411](https://user-images.githubusercontent.com/1313428/160489753-e6db5ab7-7d5a-43c9-b6ff-9169ad072e64.png)

**Comment by Lucasmiguelmac** [comment]
What I meant is that in autocomplete field, when you set multiple to `false`:
![image](https://user-images.githubusercontent.com/49038881/160490331-89f70549-6e93-496f-80f7-b18a89037eda.png)
The form will look like this:
![image](https://user-images.githubusercontent.com/49038881/160490485-f3036ae8-83ec-4f5d-b293-655ed7d540c1.png)

**Comment by kamalkech** [comment]
![DeepinScreenshot_select-area_20220328213413](https://user-images.githubusercontent.com/1313428/160491047-eb2c182d-dc15-4326-beb8-f2fae21ad5fc.png)

**Comment by Lucasmiguelmac** [comment]
Ok then, thank you very much. So, for those in the future looking for an answer, you gotta manually set `placeholder` to `""`.
