### ISSUE TITLE
Multiple forms in the same app

### ISSUE THREAD

**Issue by Lucasmiguelmac** [arabdevelop/svelte-formly#42]
How should we go about using more than one form in our app?. That is, in the current state, two or more Form components can't share one state.

[Example repl](https://svelte.dev/repl/a062b87dd7574971b8f9113931460079?version=3.44.2)

**Comment by Lucasmiguelmac** [comment]
I'm using the following piece of code to solve this in the moment. But being able to two-way bind the values for each individual form with the `bind:formValues` syntax would be the best as a feature to add.

```ts
  import { Field, valuesForm } from "svelte-formly";

let myFormsState = {};
valuesForm.subscribe((changedFields: any) => {
    formValues.values ={...formValues.values, ...changedFields.values};
  })
```

**Comment by kamalkech** [comment]
don t complicate your app, try to create two components and create a form in each component and if u need to merge all values of forms u can use dispatcher

**Comment by Lucasmiguelmac** [comment]
How would I use dispatcher? As far as I know, all forms in my app share the same store.

**Comment by kamalkech** [comment]
- First of all, your example is not a multiple forms, you use one form with two fields array of objects, so cannot understand why you complicate your code !!
```
<form on:submit|preventDefault="{onSubmit}">
  <Field fields={fields1} />
  <Field fields={fields2} />
</form>
```

- So if you need to create multiple forms should create two components and for each create own form then import them in parent component.
```
<Form1 />
<Form2 />
```

for more details check this example : https://svelte.dev/repl/beb7d6c1d87b40079b38ef60e89e5fdd?version=3.44.2

**Comment by Lucasmiguelmac** [comment]
> * First of all, your example is not a multiple forms, you use one form with two fields array of objects, so cannot understand why you complicate your code !!
> 
> 
> ```
> <form on:submit|preventDefault="{onSubmit}">
>   <Field fields={fields1} />
>   <Field fields={fields2} />
> </form>
> ```
> 
>     * So if you need to create multiple forms should create two components and for each create own form then import them in parent component.
> 
> 
> ```
> <Form1 />
> <Form2 />
> ```

Okay, but how do I initalize those `<Form2>` and `<Form1>` components? How do I access their respective stores separately.

**Comment by AhsanNissar** [comment]
I think this is a very vague argument that having two forms in same components would complicate the app. Svelte fornly should allow us to created multiple forms on same. As far as I know if I give a different variable name instead of `fields` then that does not render the form and this should not happen.

**Comment by Lucasmiguelmac** [comment]
> I think this is a very vague argument that having two forms in same components would complicate the app. Svelte fornly should allow us to created multiple forms on same. As far as I know if I give a different variable name instead of `fields` then that does not render the form and this should not happen.

You seem to never have tried this. I didn't come with this out of thin air, since both `<Field>` components share a same store, when you try to submit a form, you will submit only the one that was last modified. When the expected thing would be to submit only the one you are trying to submit, but there's no way to isolate a `valuesForm` for a single form.

**Comment by kamalkech** [comment]
@Lucasmiguelmac exactly 
@AhsanNissar first thank u for using the package, we already working for next version with big updates and fixe many issues, to make package more easy to integrate.

**Comment by kamalkech** [comment]
@AhsanNissar @Lucasmiguelmac https://svelte.dev/repl/a37e36748ac04ae4877772a97b797d07?version=3.48.0

**Comment by Lucasmiguelmac** [comment]
You're the best Kamal! This library is getting more amazing with time. We only need default values for radio buttons and we are there!

**Comment by kamalkech** [comment]
@Lucasmiguelmac thank u, for radio with default value => https://svelte.dev/repl/119285de53d84f38a7228b3f39895bbb?version=3.48.0
