### ISSUE TITLE
 Feature Request: Default values for radio buttons

### ISSUE THREAD

**Issue by Lucasmiguelmac** [arabdevelop/svelte-formly#45]
As of today, we are not able to set default values for radio buttons with a value field like we can do with other fields.

```js
  const fields = [
	{
		"type": "radio",
		"name": "my-name",
		"extra": {
			"items": [
				{
					"value": 1,
					"title": "One",
					"name": "one"
				},
				{
					"value": 2,
					"title": "Two",
					"name": "two"
				},
				{
					"value": 3,
					"title": "Three",
					"name": "three"
				},
				{
					"value": 4,
					"title": "Four",
					"name": "four"
				}
			]
		},
		"value": 4 // --> won't do anything
}
  ];
```

Example [repl](https://svelte.dev/repl/4a3cd8b1442b480e9247559fcdcb41e4?version=3.44.2).

**Comment by Lucasmiguelmac** [comment]
Just made a [PR](https://github.com/arabdevelop/svelte-formly/pull/46) for this. It should fix this. Though I'm not sure on how to test it.

**Comment by kamalkech** [comment]
@Lucasmiguelmac thank you for your investigation, i already working to build next version with different updates and fixes many issues
