### ISSUE TITLE
Select first item

### ISSUE THREAD

**Issue by webfrank** [arabdevelop/svelte-formly#57]
When using a select field, if left untouched, the shown selected item is not really selected (not returned as values) and it is null in the on:update event.

**Comment by kamalkech** [comment]
@webfrank thank u for ur investigation, as you said if left untouched ofc the value it will be null because u need add to default value.
try to test using  this repl bellow:
[https://svelte.dev/repl/fa8e6cd0c671439e84eb44bca73fc9e3?version=3.49.0](https://svelte.dev/repl/fa8e6cd0c671439e84eb44bca73fc9e3?version=3.49.0)

**Comment by kamalkech** [comment]
@webfrank i close this task because get no feedback

**Comment by webfrank** [comment]
Hi, sorry for late feedback. It seems that even if I set the value the first item is not reported as selected.

This is field config:
```
{
  type: 'select',
  name: 'kind',
  value: 'temperature',
  attributes: {
    id: 'kind',
    label: 'Metric',
    classes: ['form-control', 'mb-2']
  },
  extra: {
    options: [
      {
        value: 'temperature',
        title: 'Temperature'
      },
      {
        value: 'humidity',
        title: 'Humidity'
      },
      {
        value: 'batteryPercentage',
        title: 'Battery'
      }
    ]
  }
}
```

and this is the renderd form

![Schermata 2022-08-02 alle 15 44 40](https://user-images.githubusercontent.com/4688664/182390310-8ceee81b-7d8b-41ff-b629-f27ad254ff67.png)

but from the on:update handler I got this:

![Schermata 2022-08-02 alle 15 48 06](https://user-images.githubusercontent.com/4688664/182390643-d7bd7ccf-ed09-414e-b547-c7675977c683.png)

`kind` is supposed to be `temperature` but instead is null.
